query GeneralSettings {
    generalSettings {
        title
        description
        url
        featuredImageUrl
        featuredImageAlt
        featuredImageMime
        featuredImageWidth
        featuredImageHeight
    }
}